CATEGORY_CHOICES = (
    ('Concerts', 'Concerts'),
    ('Conferences', 'Conferences'),
    ('Workshops', 'Workshops'),
    ('Seminars', 'Seminars'),
    ('Webinars', 'Webinars'),
    ('Sports', 'Sports'),
    ('Exhibitions', 'Exhibitions'),
    ('Meetups', 'Meetups'),
    ('Networking', 'Networking'),
    ('Parties', 'Parties'),
    ('Festivals', 'Festivals'),
    ('Charity', 'Charity'),
    ('Arts & Culture', 'Arts & Culture'),
    ('Education', 'Education'),
    ('Technology', 'Technology'),
    ('Food & Drink', 'Food & Drink'),
    ('Health & Wellness', 'Health & Wellness'),
    ('Family & Kids', 'Family & Kids'),
    ('Other', 'Other'),
)